name: Notify Discord on New Announcement Discussion

on:
  discussion:
    types: [created]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    if: github.event.discussion.category.name == 'announcements'
    steps:
      - name: Send message to Discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: 0x00ff00
          status: ${{ job.status }}
          title: ${{ github.event.discussion.title }}
          description: ${{ github.event.discussion.body }}
          url: ${{ github.event.discussion.html_url }}
          username: GitHub Announcements Bot
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          nodetail: false
          nofail: true
          nocontext: true
          noprefix: true
          # content: "Hey @everyone, we have a new announcement!"
