name: Notify Discord on New Announcement Discussion

on:
  discussion:
    types: [created]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    if: github.event.discussion.category.name == 'announcements'
    steps:
      - name: Send message to Discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: https://discord.com/api/webhooks/1102520462011027486/SyXN4msDHQhxhRnJcLeJ4qWVno39TPFGfHi45vOym2XGHDpARW23rQGzjRkjuJu6YDk2
          status: ${{ job.status }}
          title: "New Announcement: ${{ github.event.discussion.title }}"
          description: ${{ github.event.discussion.body }}
          color: 0x00ff00
          url: ${{ github.event.discussion.html_url }}
          username: GitHub Announcements Bot
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          nodetail: false
          nofail: true
          nocontext: true
          noprefix: true
          content: "Hey <@&ROLE_ID>! We have a new announcement!" # Replace ROLE_ID with your Discord role ID
